name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ropebwt
      run: cd ropebwt2 ; make ; cd ..
    - name: htslib
      run: cd htslib ; make ; cd ..
    - name: make
      run: make
