name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: libdeflate
      run: make
      working-directory: ./libdeflate
    - name: abPOA
      run: make
      working-directory: ./abPOA
    - name: rapidfuzz
      run: mkdir build
      run: cd build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
      run: cmake --build .
      working-directory: ./rapidfuzz-cpp
    - name: ropebwt
      run: make
      working-directory: ./ropebwt2
    - name: htslib
      run: make
      working-directory: ./htslib
    - name: make
      run: make
